# Generated by Django 5.2.7 on 2025-10-19 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="ModelCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_id", models.CharField(max_length=120)),
                ("model_name", models.CharField(max_length=120)),
                ("model_type", models.CharField(max_length=50)),
                ("base_url", models.URLField(max_length=300)),
                ("context_size", models.PositiveIntegerField(default=4096)),
                ("max_tokens", models.PositiveIntegerField(default=4096)),
                ("completion_mode", models.CharField(default="Chat", max_length=30)),
                ("vision_support", models.BooleanField(default=False)),
                ("function_call_support", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="llm.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["provider__slug", "model_name"],
                "unique_together": {("provider", "model_id")},
            },
        ),
        migrations.CreateModel(
            name="ProviderApiKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable alias, e.g. API_KEY1", max_length=100
                    ),
                ),
                ("secret", models.TextField()),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="llm.provider",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "name")},
            },
        ),
    ]
