# Generated by Django 5.2.7 on 2025-10-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerapikey",
            name="api_base",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="providerapikey",
            name="organization",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
