# Generated by Django 5.2.7 on 2025-10-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_providerapikey_api_base_providerapikey_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcredential",
            name="organization",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="modelcredential",
            name="secret",
            field=models.TextField(blank=True, null=True),
        ),
    ]
