# Generated by Django 5.2.7 on 2025-10-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_modelcredential_organization_modelcredential_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelcredential",
            name="base_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
