# Generated by Django 5.2.7 on 2025-10-20 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0004_alter_modelcredential_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'kb_document',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('characters', models.IntegerField()),
                ('chunk_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='kb.document')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
                'db_table': 'kb_chunk',
                'ordering': ['chunk_number'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Knowledge base name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Knowledge base description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delimiter', models.CharField(default='\\n\\n', max_length=100)),
                ('max_length', models.IntegerField(default=1024)),
                ('overlap', models.IntegerField(default=50)),
                ('replace_spaces', models.BooleanField(default=True)),
                ('delete_urls', models.BooleanField(default=False)),
                ('qa_format', models.BooleanField(default=False)),
                ('qa_language', models.CharField(default='English', max_length=50)),
                ('question_flag', models.CharField(default='Q: ', max_length=50)),
                ('answer_flag', models.CharField(default='A: ', max_length=50)),
                ('qa_max_length', models.IntegerField(default=1024)),
                ('index_method', models.CharField(choices=[('hq', 'High Quality'), ('eco', 'Economical')], default='hq', max_length=10)),
                ('retrieval_mode', models.CharField(choices=[('vector', 'Vector'), ('fulltext', 'Full-Text'), ('hybrid', 'Hybrid')], default='vector', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('embedding_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llm.modelcredential')),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Bases',
                'db_table': 'kb_knowledge_base',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kb.knowledgebase'),
        ),
    ]
