# Generated by Django 5.2.7 on 2025-10-20 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('general', 'General'), ('qa', 'Using Q&A')], help_text='Type of chunking: General or Q&A', max_length=10)),
                ('delimiter', models.CharField(default='\\n\\n', max_length=100)),
                ('max_length', models.IntegerField(default=1024)),
                ('overlap', models.IntegerField(default=50)),
                ('replace_spaces', models.BooleanField(default=True)),
                ('delete_urls', models.BooleanField(default=False)),
                ('qa_format', models.BooleanField(default=False)),
                ('qa_language', models.CharField(default='English', max_length=50)),
                ('question_flag', models.CharField(default='Q: ', max_length=50)),
                ('answer_flag', models.CharField(default='A: ', max_length=50)),
                ('qa_max_length', models.IntegerField(default=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chunk Settings',
                'verbose_name_plural': 'Chunk Settings',
                'db_table': 'kb_chunk_settings',
            },
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='answer_flag',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='delete_urls',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='delimiter',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='max_length',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='overlap',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='qa_format',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='qa_language',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='qa_max_length',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='question_flag',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='replace_spaces',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_settings',
            field=models.ForeignKey(blank=True, help_text='Chunking configuration', null=True, on_delete=django.db.models.deletion.CASCADE, to='kb.chunksettings'),
        ),
    ]
