# Generated by Django 5.2.7 on 2025-10-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_chunksettings_remove_knowledgebase_answer_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='chunk_id',
            field=models.CharField(max_length=100),
        ),
    ]
