# Generated by Django 5.2.7 on 2025-10-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_chunk_chunk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Total number of chunks'),
        ),
        migrations.AddField(
            model_name='document',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Total word count of the document'),
        ),
    ]
