# Generated by Django 5.2.7 on 2025-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_document_chunk_count_document_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='chunk_count',
        ),
        migrations.RemoveField(
            model_name='document',
            name='word_count',
        ),
        migrations.AddField(
            model_name='chunk',
            name='word_count',
            field=models.IntegerField(default=0, help_text='Word count of this chunk'),
        ),
    ]
