# Generated by Django 5.2.7 on 2025-10-21 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_add_tag_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, help_text='Knowledge base this tag belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='kb.knowledgebase'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Tag name', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'knowledge_base')},
        ),
        migrations.DeleteModel(
            name='KnowledgeBaseTag',
        ),
    ]
