# Generated by Django 5.2.7 on 2025-10-21 13:21

from django.db import migrations, models
import django.db.models.deletion


def populate_knowledge_base_for_tags(apps, schema_editor):
    """Populate knowledge_base for existing tags that have null values"""
    Tag = apps.get_model('kb', 'Tag')
    KnowledgeBase = apps.get_model('kb', 'KnowledgeBase')
    
    # Get the first knowledge base as default
    first_kb = KnowledgeBase.objects.first()
    if first_kb:
        # Update all tags with null knowledge_base to use the first knowledge base
        Tag.objects.filter(knowledge_base__isnull=True).update(knowledge_base=first_kb)
    else:
        # If no knowledge base exists, delete all tags with null knowledge_base
        Tag.objects.filter(knowledge_base__isnull=True).delete()


def reverse_populate_knowledge_base(apps, schema_editor):
    """Reverse operation - this is not reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0008_add_tag_status"),
    ]

    operations = [
        # First, populate any null knowledge_base values
        migrations.RunPython(
            populate_knowledge_base_for_tags,
            reverse_populate_knowledge_base,
        ),
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='tag',
            name='knowledge_base',
            field=models.ForeignKey(
                help_text='Knowledge base this tag belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tags',
                to='kb.knowledgebase'
            ),
        ),
    ]
